gmp: Fix C23 compatibility patch to work with older host compilers
The patch added in 1e9bf8151513b054f60f34bc89507c31dc242cf0 changes
the definition of the function `g` used in `configure` tests from
`void g(){}` to `void g(int,t1 const*,t1,t2,t1 const*,int){}`.

However, omitting parameter names in function definitions is a C23 feature.
This thus causes configuration to fail with a GCC 9 host compiler:

```c
conftest.c: In function 'g':
conftest.c:7:8: error: parameter name omitted
    7 | void g(int,t1 const*,t1,t2,t1 const*,int){}
      |        ^~~
conftest.c:7:12: error: parameter name omitted
    7 | void g(int,t1 const*,t1,t2,t1 const*,int){}
      |            ^~~~~~~~~
conftest.c:7:22: error: parameter name omitted
    7 | void g(int,t1 const*,t1,t2,t1 const*,int){}
      |                      ^~
conftest.c:7:25: error: parameter name omitted
    7 | void g(int,t1 const*,t1,t2,t1 const*,int){}
      |                         ^~
conftest.c:7:28: error: parameter name omitted
    7 | void g(int,t1 const*,t1,t2,t1 const*,int){}
      |                            ^~~~~~~~~
conftest.c:7:38: error: parameter name omitted
    7 | void g(int,t1 const*,t1,t2,t1 const*,int){}

Signed-off-by: Manuel Bergler <berglerma@gmail.com>