gettext: Fix cross build for mingw
Cherry-pick the following commit from gnulib:
  ctime, localtime, tzset, wcsftime: Fix env access (regr. 2024-02-09).
  https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=commit;h=92cdf62b56462b914193c7770440e505a37c2526

This upstream patch fixes the following error:
  [ERROR]    .../.build/HOST-x86_64-w64-mingw32/pru-elf/src/gettext/gettext-tools/gnulib-lib/localtime.c:66:24: error: initialization of 'char *' from incompatible pointer type 'char **' [-Wincompatible-pointer-types]
  [ALL  ]       66 |         for (char *s = env; *s != NULL; s++)

Crosstool configuration:
  build:  x86_64-unknown-linux-gnu
  host:   x86_64-w64-mingw32
  target: pru-elf

Signed-off-by: Dimitar Dimitrov <dimitar@dinux.eu>
(cherry picked from commit 0c615353476c84f680551541b7e4f9453b7ee855)
Signed-off-by: Stephanos Ioannidis <root@stephanos.io>