cc/go: Select IPv6 support if Go Lang is enabled
GCC Go depends on IPv6 support in it's libc.
If the libc is uClibc, enable IPv6 support:

======================================================================
.build/src/gcc-5.2.0/libgo/go/net/sockoptip_posix.go:35:104: error:
reference to undefined identifier 'syscall.IPV6_MULTICAST_IF'
======================================================================

Signed-off-by: Bryan Hundven <bryanhundven@gmail.com>