gcc: don't use unwind-dw2-fde-dip with xtensa-elf targets
This fixes build for elf target with windowed xtensa core that currently
breaks with the following error message:

  unwind-dw2-fde-dip.c:36:40: fatal error: elf.h: No such file or directory

Signed-off-by: Max Filippov <jcmvbkbc@gmail.com>