Unbreak *-uclibc with native GDB.
Currently, native GDB 7.11 fails to build with uClibc-ng due to
undefined reference to _obstack_free.

On IRC
[http://crosstool-ng.osuosl.org/download/ibot-logs/2016-02-28.html], it
has been suggested to disable obstack in uClibc configuration. I think
it is a workaround rather than a fix: if another library/app needs
obstack, this leaves no viable configuration. IMO, if uClibc seeks to
mimic the glibc API, it should also provide _obstack_free call (an
alias for which it already has, even though commented out).

Signed-off-by: Alexey Neyman <stilor@att.net>