Restore 1.0.17 and make 1.0.18 experimental.
1.0.18 changed the dependencies for the static libraries, notably
in libc/Makefile.in. This resulted in packing a lot of unrelated
stuff into libc.a, including (sic!) a nested .a library and stuff
from other libraries such as libdl. This results in a failure to
statically link with thus created libc.a:

.../libc.a(libdl.os):(.literal+0x74): undefined reference to `_dl_tlsdesc_return'

This was breaking xtensa-*-uclibc sample.

Signed-off-by: Alexey Neyman <stilor@att.net>