moxiebox: Use newlib 4.2
moxie-unknown-moxiebox has problems building with newlib 4.3

  ld: /lib/libc.a(libc_a-closer.o): in function `_close_r':
  newlib/libc/reent/closer.c:47: undefined reference to `_close'

There are some Makefile changes in newlib 4.3 and it's likely previously
this config was picking up `_close` from libsim.a. For now just pin the
newlib version back to 4.2 in the moxie-unknown-moxiebox config.

Resolves #2036
Signed-off-by: Chris Packham <judge.packham@gmail.com>